services:
  db:
    image: postgres:15
    container_name: postgresql-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: food-order-database
